################################################################################
##
##  Purpose: Define a miroservice for interfacing with Blinkt GPIO Raspberry Pi
##    single-board computer.
##
##  Email: christopher.page@ca.com
##
################################################################################
version: '3'
services:
  blinkt:
    ## iot_sys-blinkt does not require priviledged container/os access
    image: phriscage/iot_sys-blinkt:0.3.0
    volumes:
      - /sys:/sys
    ports:
      - 8000:8080
    deploy:
      mode: global
      placement:
        constraints:
          - node.role != manager
